services:
  mlflow:
    build: .
    container_name: mlflow_container
    ports:
      - "5001:5001"
    volumes:
      - ./src/models:/home/mlflow/src/models # MLflow models
      - ./src/mlruns:/home/mlflow/src/mlruns # MLflow tracking server
      # add more volumes if needed
    environment:
      - file:///home/mlflow/src/mlruns
