services:
  mlflow:
    build: .
    container_name: mlflow_container
    ports:
      - "5001:5001"
    volumes:
      - ./src:/home/mlflow/src
      - ./src/mlruns:/home/mlflow/src/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///home/mlflow/src/mlruns
